### ISSUE TITLE
Cannot personalize emails using plugins

### ISSUE THREAD

**Issue by kdoonboli** [responsiv/campaign-plugin#27]
I added some logging messages. So it appears if I try to embed a plugin in there, the plugin execution happens once per campaign, regardless of the number of users. And the Plugin runs that one time only on 'Template Refresh'. That would mean I can't personalize emails for different users, That's a big issue for me. I wanted to send personalized User Activity emails using this plugin  :/

What I wish I could do:
- pass user data to the embedded plugin - such as user's email address e.g. {% component 'myplugin' userEmail=email%} - actually I wish I could've passed user's rainlab userid if recipient was a user (but I can still look up user based on email). But even at the moment I can't seem to be able to pass any user information to the plugin. If that is possible, how?

- refresh the template the number of times for the number of users (allow email personalization for users).
- refresh the template right before sending emails as opposed to refreshing at campaign creation

thanks,

**Comment by daftspunk** [comment]
This is by design, a template campaign is compiled and then sent to everyone. Like a brochure or a flyer, it doesn't include personalized information. User activity and things like this would be sent using [the standard mail process](http://octobercms.com/docs/services/mail). We don't plan to add any personalization features to this plugin at this stage.
