### ISSUE TITLE
User interface not translatable

### ISSUE THREAD

**Issue by KGE** [responsiv/campaign-plugin#28]
Would be nice to have strings extracted to the "lang array" so that user interface can be easily translated to other languages if needed

**Comment by manuelbua** [comment]
I would be more than happy to contribute with a free Italian translation for this: @daftspunk, do you have any indication on how to best tackle this, in-place translations aside?

**Comment by daftspunk** [comment]
Feel free to translate this plugin and [send a message](https://octobercms.com/author/Responsiv) when its ready. We'll reply with an email that you can use to send the zip archive, and publish it from there.

**Comment by manuelbua** [comment]
I was asking for indications because, well, there are none: should i proceed with in-place translations in partials and views? Should i use placeholder such as `{{ 'partial.code'|_}}` and `{{ 'partial.code'|__(count)}}` to also handle plurals? Any convention to use for this?

There is no infrastructure in this plugin to correctly handle all edge cases, should one happen, so i was asking for some indication.. or, even better, do you plan to export the messages into a PHP array ala plugins? If so, i would wait for it and then i could send you the translation file alone.

**Comment by daftspunk** [comment]
I think this issue refers to the backend UI where it is hard coded in English, other plugins (eg: RainLab.Blog) use language keys everywhere.

I'm not sure if you can use the `|_` filter in mail templates, you probably can!

**Comment by manuelbua** [comment]
Uh sorry i didn't state that i meant the backend UI was what i wanted to translate: i would like to do it but since it's hard-coded i thought you probably wanted to have those extracted these into some translatable form instead, so that other languages can be supported too.

Since i have a very imminent deadline on a project using this, i'm not sure i'll have the time to do anything better than an in-place localization, so i was thinking on how to organize things a bit..

**Comment by daftspunk** [comment]
@manuelbua Can you give me an example of what needs to be translated?

**Comment by KGE** [comment]
I think he refers to the backend UI too, that like you wrote above is hard-coded in english, and since this is a **premium** plugin I think it should be at least open for localization

**Comment by manuelbua** [comment]
Yes @KGE got it right, i meant the backend UI as i stated in my last comment: the hard-coded strings are English and can't really be translated the October way..

**Comment by daftspunk** [comment]
Translation keys have been added in v1.3.0
