### ISSUE TITLE
Error when duplicating a campaign

### ISSUE THREAD

**Issue by smartscripts-nl** [responsiv/campaign-plugin#48]
When I duplicate a campaign, I receive this error message in a popup: "Illegal offset type". The new campaign is created nontheless.

In the log I see an entry reflecting this error:

[2017-11-15 13:19:35] production.ERROR: ErrorException: Illegal offset type in [path-to-october-folder]/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php:139

**Comment by smartscripts-nl** [comment]
If required, I can send a full stack trace.

**Comment by datune** [comment]
@daftspunk This error still persists to this day. Can you please update your plugin?

**Comment by joebuonocore** [comment]
Ran into this today, but I haven't figured out a real solution.

Seems to be centric to the duplicating of the message-list pivot records. Commenting out line 218 in the Message model duplicates with no error message.

If I can come up with a better fix at a later date, I will update here.

**Comment by Johardmeier** [comment]
Still a Problem.

**Comment by daftspunk** [comment]
Thanks. Will take a look soon

**Comment by daftspunk** [comment]
This was a complex issue introduced in [the October library some time ago](https://github.com/octobercms/library/commit/58f1b1c6ab741d45b17aa63589aff81cf572948c), it has been fixed in https://github.com/octobercms/library/commit/9210441cee275e731bd98e4a8db334ba4fdcc4fd and will be available in build 465+

A backwards compatibility fix has also been introduced in v1.2.4 of the campaign plugin. You may now update to receive the fix. Which was to change this line in the `duplicateCampaign` function of the `Message` model:

```
$model->subscriber_lists = $this->subscriber_lists->all();
```

Thanks for your patience with this issue!
